[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools_scm]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[project]
name = "napari-manual-transforms"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
license = "MIT"
keywords = []
requires-python = ">=3.11"
classifiers = []

dependencies = [
  "ndimreg",
  "cachetools",
]

[project.optional-dependencies]
cuda12 = [
  "cupy-cuda12x>=13.3.0",
  "cucim-cu12>=24.10.0",
]

[project.scripts]
imreg = "napari_manual_transforms._imreg:app"
