[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools_scm]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[tool.uv.sources]
imreg3d = { path = "../imreg3d" }

[project]
name = "napari-manual-transforms"
version = "0.0.0"
description = ""
authors = []
readme = "README.md"
license = "MIT"
keywords = []
requires-python = ">=3.11"
classifiers = []

# TODO: Pin dependencies to a minimum version.
dependencies = [
  "imreg3d",
  "cachetools",
]

[project.scripts]
imreg = "napari_manual_transforms._imreg:app"
